preload = /home/dzejkob/important images/New_Project.png
preload = /home/dzejkob/important images/bigwallpaper.jpg

wallpaper = eDP-1,/home/dzejkob/important images/New_Project.png
wallpaper = DP-10,/home/dzejkob/important images/bigwallpaper.jpg

# Optional settings
ipc = off

