preload = /home/dzejkob/important images/New_Project.png
preload = /home/dzejkob/important images/tenor.jpg

wallpaper = eDP-1,/home/dzejkob/important images/New_Project.png
wallpaper = HDMI-A-1,/home/dzejkob/important images/tenor.jpg


# Optional settings
ipc = off

